import { Role } from '@prisma/client';

/** Permissões granulares mapeadas por papel (RBAC estendido). */
export const ROLE_PERMISSIONS: Record<Role, readonly string[]> = {
  [Role.ADMIN]: [
    'auth:sessao',
    'clientes:criar',
    'clientes:ler',
    'clientes:atualizar',
    'clientes:excluir',
    'solicitacoes:criar',
    'solicitacoes:ler',
    'solicitacoes:atualizar',
    'solicitacoes:excluir',
    'solicitacoes:portaria',
    'solicitacoes:gate',
    'solicitacoes:patio',
    'solicitacoes:saida',
    'faturamento:ler',
    'faturamento:criar',
    'nfse:emitir',
    'nfse:cancelar',
    'nfse:consultar',
    'boletos:registrar',
    'boletos:atualizar',
    'relatorios:operacional',
    'relatorios:financeiro',
    'dashboard:operacional',
    'dashboard:financeiro',
    'dashboard:financeiro_executivo',
    'dashboard:performance',
    'comercial:pricing',
    'users:criar',
    'auditoria:ler',
  ],
  [Role.GERENTE]: [
    'auth:sessao',
    'clientes:criar',
    'clientes:ler',
    'clientes:atualizar',
    'clientes:excluir',
    'solicitacoes:criar',
    'solicitacoes:ler',
    'solicitacoes:atualizar',
    'solicitacoes:excluir',
    'solicitacoes:portaria',
    'solicitacoes:gate',
    'solicitacoes:patio',
    'solicitacoes:saida',
    'faturamento:ler',
    'faturamento:criar',
    'nfse:emitir',
    'nfse:cancelar',
    'nfse:consultar',
    'boletos:registrar',
    'boletos:atualizar',
    'relatorios:operacional',
    'relatorios:financeiro',
    'dashboard:operacional',
    'dashboard:financeiro',
    'dashboard:financeiro_executivo',
    'dashboard:performance',
    'comercial:pricing',
    'auditoria:ler',
  ],
  [Role.OPERADOR_PORTARIA]: [
    'auth:sessao',
    'clientes:ler',
    'solicitacoes:criar',
    'solicitacoes:ler',
    'solicitacoes:atualizar',
    'solicitacoes:portaria',
    'dashboard:operacional',
    'dashboard:performance',
  ],
  [Role.OPERADOR_GATE]: [
    'auth:sessao',
    'clientes:ler',
    'solicitacoes:ler',
    'solicitacoes:atualizar',
    'solicitacoes:gate',
    'solicitacoes:saida',
    'dashboard:operacional',
    'dashboard:performance',
  ],
  [Role.OPERADOR_PATIO]: [
    'auth:sessao',
    'clientes:ler',
    'solicitacoes:ler',
    'solicitacoes:patio',
    'dashboard:operacional',
    'dashboard:performance',
  ],
  [Role.CLIENTE]: [
    'auth:sessao',
    'clientes:ler',
    'solicitacoes:ler',
    'faturamento:ler',
    'portal:solicitacao:aprovar',
  ],
};

export function permissionsForRole(role: Role): string[] {
  return [...ROLE_PERMISSIONS[role]];
}
